### ISSUE TITLE
Python script not working with the latest version of Immich v1.99.0

### ISSUE THREAD

**Issue by happytaz** [clumsyCoder00/Immich-Tools#1]
With admin API, orphans are detected but unable to delete.  I get the following error message:

An error occurred: 400 Client Error: Bad Request for url: http://192.168.1.100:2283/api/asset

With non-admin API, orphans aren't detected at all:

✖ Failed to fetch assets: 403 Client Error: Forbidden for url: http://192.168.1.100:2283/api/audit/file-report

I also couldn't get the untracked script to work.  I get the following error:

move_untracked_files.sh: 22: Bad substitution

**Comment by malavolti** [comment]
I meet the same problem on Immich version 1.105.1. @clumsyCoder00 can you help us, please?

**Comment by clumsyCoder00** [comment]
I revised the python script to prompt for the user API key rather than manually modifying the script. Two separate API keys are needed for this. One for the admin account to generate the list of offline files, a second for the account to which the assets belong. Let me know if you have any issues!

**Comment by malavolti** [comment]
Dear @clumsyCoder00,

can you suggest me how I get 2 API key if I am the Admin and also a User?

Can I use the same API key for both?

Thank you so much!
Marco

**Comment by clumsyCoder00** [comment]
If you're managing your photos with a single account in immich, you should be able to just remove offline files directly through the library GUI. After further review of the developments of the last couple iterations of the server .104 & .105, I'm going to depreciate this script, as it is no longer necessary to use this as a workaround.

**Comment by malavolti** [comment]
I'm sorry for all disturb @clumsyCoder00, but can you tell me how I can fix the "OFFLINE PATHS" with the Library GUI?

Apparently the "Repair All" button doesn't work.

Thank you for all your help!
Marco
